(* From a reduction graph structure
   that finds individual edges
   in the labeled di-graph `G` of rewrites,
   construct a reduction graph structure
   that finds full normalization paths
   in the free category on `G`
   by iterating individual rewrites. *)
functor IterateReductionGraph (G : LABELEDDIGRAPH) =
struct
  (* A reference to the free category on `G`. *)
  structure C = FreeCategory(G)

  (* References to types of reduction graph structures. *)
  structure RG = ReductionGraphOf(G)
  structure RC = ReductionGraphOf(CategoryIntoLabeledDigraph(C))

  (* For a reduction graph `r` and initial form `x`,
     the list of (rewrite, new-form) pairs generated by iterated
     stepping of `x` according to `r`. *)
  fun stepsFrom
      (r: RG.reducer) (x: G.Node.t)
      : (G.Edge.t * G.Node.t) LazyList.lazylist =
    LazyList.generate x (fn y =>
      case #step r y of
        NONE => NONE
      | SOME (a, z) => SOME ((a, z), z) )

  (* For a reduction graph structure `r` in the labeled di-graph `g`,
     constructs a reduction graph structure in the free category on `G`
     by iterated stepping according to `r`. *)
  fun iterate (r: RG.reducer) : RC.reducer = {
    step = fn x =>
      let
        val steps = stepsFrom r x
      in
        case LazyList.last steps of
          NONE => NONE
        | SOME (_, z) => SOME (steps, z)
      end }
end
