structure LazyList =
struct
  (* The type of lists whose tails are generated by an unevaluated thunk. *)
  datatype 'a lazylist =
      Nil
    | Cons of 'a * (unit -> 'a lazylist)

  (* Append two lists. *)
  fun append (s1: 'a lazylist, s2: 'a lazylist) : 'a lazylist =
    case s1 of
      Nil => s2
    | Cons (x, f) => Cons (x, fn () => append (f (), s2))

  (* Generate a list using a state machine. *)
  fun generate (init: 's) (step: 's -> ('a * 's) option) : 'a lazylist =
    case step init of
      NONE => Nil
    | SOME (x, next) => Cons (x, fn () => generate next step)

  (* Retrieve the last element of a list if it exists. *)
  fun last (s: 'a lazylist) : 'a option =
    case s of
      Nil => NONE
    | Cons (x, f) => SOME (
      case last (f ()) of
        NONE => x
      | SOME x' => x' )
end
