(* An interface for finite or infinite streams generated by state machines. *)
signature STREAM =
sig
  (* The type of elements emit by streams. *)
  type elem

  (* The type of states for stream generators. *)
  type state

  (* The type of streams. *)
  type stream

  (* Shorthand for the result of probing a generator with states from `'s`.
     `NONE` signals termination. *)
  type 's result = (elem * 's) option

  (* Package a generating state machine into a stream. *)
  val make : state * (state -> state result) -> stream

  (* Probe a stream, resulting in an element
     and a new stream with the remaining elements,
     or `NONE` signaling termination. *)
  val step : stream -> stream result
end
