(* An interface for finite or infinite streams generated by state machines,
   which must also be equipped with the empty stream and stream appendage. *)
signature STREAMMONOID =
sig
  include STREAM

  (* The empty stream. *)
  val empty : stream

  (* Append two streams. *)
  val append : stream * stream -> stream
end
